# constantes.py

# --- CÓDIGOS DE PERFIL (INPUTS) ---
SOLO_ESTUDIA = "AB"
TRABAJA_MANANA = "AC"
TRABAJA_TARDE = "AD"
TRABAJA_NOCHE = "AE"

CURSA_ALGUNAS = "AF"
CURSA_TODAS = "AG"

RETOMA_ESTUDIO = "AH"
DOS_CARRERAS = "AI"