# mensajes.py

# Diccionario que mapea el CÓDIGO de la recomendación con el TEXTO a mostrar
RECOMENDACIONES = {
    "A": "Dedicar al menos una hora de atención a cada materia durante la mañana, la tarde o la noche.",
    "B": "Seguir el ritmo de la materia.",
    "C": "Rendir los finales a penas termine la cursada.",
    "D": "Tratar de promocionar las materias que lo permitan.",
    "E": "Asistir a todas las clases y tomar apuntes de los temas.",
    "F": "Dedicar un tiempo fijo a cada materia.",
    "G": "Organizar bien los tiempos por doble turno de trabajo.",
    "H": "Priorizar las materias para no sobrecargarse.",
    "I": "Motivar a continuar con la carrera.",  # Corregido de '1' a 'I'
    "J": "No tiene método de estudio.",
    "K": "Recomendar técnicas de estudio.",
    "L": "Mostrar el horario de las materias que se dictan a la mañana.",
    "M": "Recomendar clases virtuales.",
    "N": "Mostrar el horario de las materias que se dictan a la tarde.",
    "O": "Se dificulta retomar el ritmo.",
    "P": "Método de estudio.",
    "Q": "Dificultad para entender una materia.",
    "R": "Cursos nivelatorios.",
    "S": "Tutores académicos.",
    "T": "Materias troncales.",
    "U": "Aprovechar tiempo libre para avanzar las materias.",
    "V": "Clases presenciales.",
    "W": "Clases de consulta.",
    "X": "Mapa conceptual.",
    "Y": "Consultar a un compañero.",
    "Z": "Buscar en internet.",
    "AA": "Evitar la superposición horaria.",
    "BB": "Riesgo de estrés.",
    "CC": "Dedicar tiempo a actividades recreativas.",
    "DD": "Consultar planes de estudio para equivalencias.",
    "EE": "Priorizar materias comunes entre carreras.",
    "FF": "Tener disponibilidad de tiempo.",
    "GG": "Riesgo de sobrecarga académica.",
    "HH": "Necesidad de horarios de estudio flexibles.",
    "II": "Motivar para manejar el estrés académico.",
    "JJ": "Cursar en el horario en que esté más descansado, si es posible.",
    "KK": "Tener una buena organización de cursado.",
    "LL": "Plan de horarios.",
    "MM": "Plan de estudio diario.",
    "NN": "Priorizar carrera principal.",
    "OO": "Usar Google Calendar.", # Corregido de '00' a 'OO'
    "PP": "Llegar descansado a los parciales.",
    "QQ": "Dificultad para asistir a clases.",
    "RR": "Plan de descanso adecuado.",
    "SS": "Apoyarse en materiales adicionales o virtuales por falta de tiempo.",
    "TT": "Armar cronograma de clases."
}